---
- name: Create CTFd directory
  file:
    path: /opt/ctfd
    state: directory
    mode: '0755'

- name: Copy Docker Compose file
  copy:
    src: files/docker-compose.yml
    dest: /opt/ctfd/docker-compose.yml
    mode: '0644'

- name: Copy Nginx configuration
  copy:
    src: files/nginx.conf
    dest: /opt/ctfd/nginx.conf
    mode: '0644'

- name: Create directories for volumes
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/ctfd/CTFd/logs
    - /opt/ctfd/CTFd/uploads
    - /opt/ctfd/CTFd/CTFd
    - /opt/ctfd/CTFd/mysql
    - /opt/ctfd/CTFd/redis

- name: Start CTFd with Docker Compose
  community.docker.docker_compose:
    project_src: /opt/ctfd
    state: present
  register: output