---
- name: Deploy CTFd with Docker
  hosts: ctfd_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: present

    - name: Install Docker via script
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Install Docker Compose via binary download
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        owner: root
        group: root

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create CTFd directory
      file:
        path: /opt/ctfd
        state: directory
        mode: '0755'

    - name: Create CTFd subdirectories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/ctfd/CTFd/logs
        - /opt/ctfd/CTFd/uploads
        - /opt/ctfd/CTFd/mysql
        - /opt/ctfd/CTFd/redis

    - name: Create Docker Compose file
      copy:
        dest: /opt/ctfd/docker-compose.yml
        mode: '0644'
        content: |
          version: '3'
          services:
            ctfd:
              image: ctfd/ctfd:latest
              restart: always
              ports:
                - "8000:8000"
              environment:
                - UPLOAD_FOLDER=/var/uploads
                - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
                - REDIS_URL=redis://cache:6379
                - WORKERS=4
                - LOG_FOLDER=/var/log/CTFd
                - ACCESS_LOG=-
                - ERROR_LOG=-
                - REVERSE_PROXY=true
                - SECRET_KEY=ctfd_secret_key_for_group_33
              volumes:
                - ./CTFd/logs:/var/log/CTFd
                - ./CTFd/uploads:/var/uploads
              depends_on:
                - db
                - cache
            nginx:
              image: nginx:latest
              restart: always
              ports:
                - "80:80"
              volumes:
                - ./nginx.conf:/etc/nginx/conf.d/default.conf
              depends_on:
                - ctfd
            db:
              image: mariadb:10.5
              restart: always
              environment:
                - MYSQL_ROOT_PASSWORD=ctfd
                - MYSQL_USER=ctfd
                - MYSQL_PASSWORD=ctfd
                - MYSQL_DATABASE=ctfd
              volumes:
                - ./CTFd/mysql:/var/lib/mysql
            cache:
              image: redis:4
              restart: always
              volumes:
                - ./CTFd/redis:/data

    - name: Create Nginx configuration
      copy:
        dest: /opt/ctfd/nginx.conf
        mode: '0644'
        content: |
          server {
            listen 80;
            server_name _;
            location / {
              proxy_pass http://ctfd:8000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
          }

    - name: Start CTFd with Docker Compose
      command: docker compose up -d
      args:
        chdir: /opt/ctfd